### ISSUE TITLE
Crash on fabric 1.17

### ISSUE THREAD

**Issue by Zano1999** [beepbeep-boop/barrenisles#4]
It crash on fabric 1.17,
Here the crash report: https://pastebin.com/RCw9nKkh

**Comment by beepbeep-boop** [comment]
right uh should be fixed in 1.0.5, also, you need to install geckolib.

**Comment by beepbeep-boop** [comment]
ill put geckolib and all in a bigger font / picture just for better reading i guess, sometimes people might miss it
